version: '3'
services:
  db-account:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: abcdefg
      POSTGRES_DB: account-database
    ports:
    - "15432:5432"
  db-backend:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: abcdefg
      POSTGRES_DB: backend-database
    ports:
    - "25432:5432"
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
    - "9000:8080"
  mailhog:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    - "1025:1025"
