version: '3'
services:
  db-resouce-server:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: abcdefg
      POSTGRES_DB: resource-server-database
    ports:
      - "15432:5432"
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "9000:8080"
  mailhog:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    - "1025:1025"
